# Generated by Django 5.1.6 on 2025-03-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='order_time',
            field=models.DateTimeField(),
        ),
    ]
