# Generated by Django 5.1.6 on 2025-03-06 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_printorder_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
