services:
  - type: web
    name: SmartDocX
    runtime: python
    region: oregon
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    buildCommand: |
      apk add --no-cache ghostscript
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn app.wsgi:application --bind 0.0.0.0:8000
